version: "3.8"

services:
  db:
    image: postgres:16
    container_name: pg
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      TZ: Europe/Moscow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

  etl_tariffs:
    build:
      context: .
      dockerfile: data/postgres/etl/Dockerfile.tariffs
    container_name: excel_to_pg_tariffs
    environment:
      PGHOST: db
      PGPORT: "5432"
      PGDATABASE: appdb
      PGUSER: appuser
      PGPASSWORD: apppass
      EXCEL_PATH: /app/input.xlsx       # файл будет скопирован в образ
      TABLE_NAME: public.tariffs
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "-u", "/app/import_excel.py"]

  etl_elevators:
    build:
      context: .
      dockerfile: data/postgres/etl/Dockerfile.elevators
    container_name: excel_to_pg_elevators
    environment:
      PGHOST: db
      PGPORT: "5432"
      PGDATABASE: appdb
      PGUSER: appuser
      PGPASSWORD: apppass
      EXCEL_PATH: /app/elevators.xlsx   # файл будет скопирован в образ
      TABLE_NAME: public.elevators
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "-u", "/app/import_elevators.py"]

  etl_parfume:
    build:
      context: .
      dockerfile: data/postgres/etl/Dockerfile.parfume
    container_name: excel_to_pg_parfume
    environment:
      PGHOST: db
      PGPORT: "5432"
      PGDATABASE: appdb
      PGUSER: appuser
      PGPASSWORD: apppass
      EXCEL_PATH: /app/parfume.xlsx   # файл будет скопирован в образ
      TABLE_NAME: public.parfume
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "-u", "/app/import_parfume.py"]

  etl_bankomats:
    build:
      context: .
      dockerfile: data/postgres/etl/Dockerfile.bankomats
    container_name: excel_to_pg_bankomats
    environment:
      PGHOST: db
      PGPORT: "5432"
      PGDATABASE: appdb
      PGUSER: appuser
      PGPASSWORD: apppass
      EXCEL_PATH: /app/bankomats.xlsx   # файл будет скопирован в образ
      TABLE_NAME: public.bankomats
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "-u", "/app/import_bankomats.py"]
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile.backend
    image: trade-defense-backend:0.1.0
    container_name: trade-defense-backend
    environment:
      - AI_BASEURL=http://host.docker.internal:8000
      - SERVER_PORT=8080
    ports:
      - "8080:8080"

volumes:
  qdrant_data:
    driver: local
  mongo_data:
    driver: local

